# Generated by Django 5.0.2 on 2024-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment_dislikes_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
