# Generated by Django 5.0.3 on 2024-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_videos'),
        ),
    ]
