# Generated by Django 5.0.3 on 2024-03-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_image_remove_post_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
